### ISSUE TITLE
no matching extension was found

### ISSUE THREAD

**Issue by sveatlo** [sphh/mopidy-autoplay#5]
I started getting a warning in mopidy log telling me that the autoplay extensions was not found and its configuration will be ignore. The funny thing is a log line later shows that the extension is loaded, so I suppose this'll be a simple name change or something similar.

Log:
```
INFO     2021-05-04 12:15:16,581 [12181:MainThread] mopidy.__main__
  Starting Mopidy 3.1.1
INFO     2021-05-04 12:15:16,602 [12181:MainThread] mopidy.config
  Loading config from builtin defaults
INFO     2021-05-04 12:15:16,603 [12181:MainThread] mopidy.config
  Loading config from file:///home/<>a/src/dotfiles/config/mopidy/mopidy.conf
INFO     2021-05-04 12:15:16,603 [12181:MainThread] mopidy.config
  Loading config from command line options
WARNING  2021-05-04 12:15:16,605 [12181:MainThread] mopidy.config
  Ignoring config section 'mopidy-autoplay' because no matching extension was found
...
INFO     2021-05-04 12:15:16,732 [12181:MainThread] mopidy_autoplay
  Mopidy-Autoplay 0.2.1
...
```

Mopidy config file:
```
...
[mopidy-autoplay]
enabled = true
# Each of the following keys can take the value "auto" (without quotes),
# in which case the values active before Mopidy was stopped are used.
# Tracklist (uris = uri, ...; index = int)
tracklist.uris = auto
tracklist.index = auto
# Tracklist options (on|off|true|false)
tracklist.consume = auto
tracklist.random = auto
tracklist.repeat = auto
tracklist.single = auto
# Playback (state = stopped|playing|paused; time_position = [in ms])
playback.state = auto
playback.time_position = auto
# Mixer (volume = [0..100]; mute = on|off|true|false)
mixer.volume = auto
mixer.mute = auto
```

**Comment by sphh** [comment]
Have you tried to put it under the section `[autoplay]`?

PS: I just noticed, that the [README.rst](https://github.com/sphh/mopidy-autoplay/README.rst) shows `[mopidy-autoplay]`, but this is (obviously) wrong.

Please tell me, if it works with the `[autoplay]` section, so that I can update the [README.rst](https://github.com/sphh/mopidy-autoplay/README.rst) file. Thanks.

**Comment by sveatlo** [comment]
Works great. Thank you for such a quick response.

**Comment by sphh** [comment]
If it were always that easy …

Fixed in https://github.com/sphh/mopidy-autoplay/commit/474c455aec509256264b5ff4656d3204189bc271
